#!/bin/sh

cgprod(){
  cd ~/main/web \
  && stashapply "prod-build" \
  && sudo rm -rf .next \
  && yarn build \
  && docker-compose down \
  && docker-compose up
}

cgc(){
  git commit -m "$(git branch --show-current | cut -d - -f 1,2): $1"
}

cgrel(){
  release_tag="$(git describe --tags --abbrev=0 | tr -d -c 0-9)"
  cmd="gh release create v$((release_tag + 1)) --generate-notes"
  echo "$cmd" && eval "$cmd"
}
