#!/bin/bash
# Used for quick and simple queries

source "$HOME/.env"
MODEL="gpt-3.5-turbo"

printf "\nLoading from GPT model: $MODEL\n\n"

content=$(curl --silent https://api.openai.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d "{
    \"model\": \"gpt-3.5-turbo\",
    \"messages\": [
      {
        \"role\": \"user\",
        \"content\": \"$1\"
      }
    ]
	}" | jq '.choices[0].message.content')

printf "Generated response:\n"
echo -e "$content"
