#!/bin/bash

source "$HOME/.env"

curl https://api.openai.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d "{
    \"model\": \"gpt-3.5-turbo\",
    \"messages\": [
      {
        \"role\": \"user\",
        \"content\": \"$1\"
      }
    ]
  }" | jq '.choices[0].message.content' | xargs -0 echo -e | glow

