#!/usr/bin/env bash

power_off=' Shutdown'
reboot=' Reboot'

option=$(printf '%s;%s' "$power_off" "$reboot" | rofi -sep ';' -dmenu -p "Power menu")

case "$option" in
  "$power_off")
    # rofi-prompt --query 'Shutdown?' && poweroff
    poweroff
  ;;
  $reboot*)
    # rofi-prompt --query 'Shutdown?' && reboot
    reboot
  ;;
esac
